# Generated by Django 4.0.1 on 2022-01-11 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=70)),
                ("image_url", models.TextField(default="")),
                ("description", models.CharField(default="", max_length=200)),
            ],
        ),
    ]
